"""Initial migration

Revision ID: 6db15f4431df
Revises: 
Create Date: 2024-12-17 11:34:42.055773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db15f4431df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bands', sa.String(length=50), nullable=False),
    sa.Column('beer', sa.String(length=50), nullable=False),
    sa.Column('abv', sa.Float(), nullable=False),
    sa.Column('tap_number', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tap_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beer')
    # ### end Alembic commands ###
